### ISSUE TITLE
Hotkey to act as toggle

### ISSUE THREAD

**Issue by sergeevabc** [medo64/QText#14]
Dear @medo64, could you be so kind to consider changing behaviour of the apps’s hotkey.
I’d like to _hide_ it the same way I invoked it in the first place, i.e. by pressing the same combo.
Right now, when the app’s window is already focused, Ctrl+Shift+Q does not hide it.

**Comment by medo64** [comment]
I will add it as an option.

**Comment by sergeevabc** [comment]
Funny thing is that QText [4.53][1] has this implemented already.

![](https://i6.imageban.ru/out/2021/03/14/ddb350050a687474328a33e392c67370.png)

[1]: https://www.medo64.com/qtext/

**Comment by medo64** [comment]
I know. :)
Thing is that the new QText is built on completely different development platform in order to accomplish proper compatibility with Linux. This unfortunately meant I had to completely rewrite it in C++ (QText 4.53 is in C#) and thus some features were lost. I'm working on getting them back. :)

**Comment by medo64** [comment]
Issue fixed in [commit b7e6d95](https://github.com/medo64/QText/commit/b7e6d95888a89969439d076ae4e1e1764b8fa46f). I'll update this issue when I compile a new release later today.

**Comment by medo64** [comment]
Feature is available in [v0.1.19](https://github.com/medo64/QText/releases/tag/v0.1.19).
